# Generated by Django 4.2.4 on 2024-03-30 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_alter_usersubscription_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='main_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_main_plan', to='video_app.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='series',
            name='main_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_main_plan', to='video_app.subscriptionplan'),
        ),
    ]
