# Generated by Django 4.2.4 on 2024-03-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_movie_main_plan_series_main_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
