# Generated by Django 4.2.4 on 2024-07-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_catagory_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
