# Generated by Django 4.2.4 on 2024-07-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_catagory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
